name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build executables
      run: npm run build:exe
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: exe/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          exe/index-linux
          exe/index-macos
          exe/index-win.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew-formulas:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Wait for release assets
      run: sleep 30
    
    - name: Update Homebrew formulas
      run: |
        # Update source-based formula
        SOURCE_URL="https://github.com/${{ github.repository }}/archive/${{ github.ref_name }}.tar.gz"
        SOURCE_SHA=$(curl -sL "$SOURCE_URL" | shasum -a 256 | cut -d' ' -f1)
        
        # Update binary formulas
        MACOS_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/index-macos"
        LINUX_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/index-linux"
        
        MACOS_SHA=$(curl -sL "$MACOS_URL" | shasum -a 256 | cut -d' ' -f1)
        LINUX_SHA=$(curl -sL "$LINUX_URL" | shasum -a 256 | cut -d' ' -f1)
        
        # Update formulas
        sed -i "s/version \".*\"/version \"${{ steps.version.outputs.VERSION }}\"/" Formula/quartr-mcp-server-bin.rb
        sed -i "s|url \".*archive.*\"|url \"$SOURCE_URL\"|" Formula/quartr-mcp-server.rb
        sed -i "s/sha256 \".*\"/sha256 \"$SOURCE_SHA\"/" Formula/quartr-mcp-server.rb
        
        # Update binary formula
        sed -i "s|url \".*index-macos\"|url \"$MACOS_URL\"|" Formula/quartr-mcp-server-bin.rb
        sed -i "s|url \".*index-linux\"|url \"$LINUX_URL\"|" Formula/quartr-mcp-server-bin.rb
        sed -i "/on_macos/,/end/ s/sha256 \".*\"/sha256 \"$MACOS_SHA\"/" Formula/quartr-mcp-server-bin.rb
        sed -i "/on_linux/,/end/ s/sha256 \".*\"/sha256 \"$LINUX_SHA\"/" Formula/quartr-mcp-server-bin.rb
    
    - name: Commit updated formulas
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/
        git commit -m "Update Homebrew formulas for version ${{ steps.version.outputs.VERSION }}" || exit 0
        git push
